-- Initial database structure


CREATE TABLE IF NOT EXISTS blocks_microblocks
(
    uid        BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT blocks_microblocks__uid__key UNIQUE,
    id         VARCHAR NOT NULL
        CONSTRAINT blocks_microblocks__pkey PRIMARY KEY,
    height     INTEGER NOT NULL,
    time_stamp BIGINT  NOT NULL
);

CREATE INDEX IF NOT EXISTS blocks_microblocks__id__idx ON blocks_microblocks (id);


CREATE TYPE operation_type AS ENUM ('invoke_script');

CREATE TABLE IF NOT EXISTS transactions
(
    uid       BIGINT         NOT NULL GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT transactions__uid__key UNIQUE,
    id        VARCHAR        NOT NULL
        CONSTRAINT transactions__pkey PRIMARY KEY,
    block_uid BIGINT         NOT NULL
        CONSTRAINT transactions__block_uid__fkey REFERENCES blocks_microblocks (uid) ON DELETE CASCADE,
    sender    VARCHAR        NOT NULL,
    tx_type   SMALLINT       NOT NULL,
    op_type   OPERATION_TYPE NOT NULL,
    operation JSONB          NOT NULL
);

CREATE INDEX IF NOT EXISTS transactions__block_uid__idx ON transactions (block_uid);
CREATE INDEX IF NOT EXISTS transactions__sender__idx ON transactions (sender);
